import type { Dict } from './types';

// English copy. Source of truth for wording: Q3 2026 investor deck + CANONICAL.md §10 word list.
// Never: "attribution", "Club", "No visit, no fee", named neighborhoods, old project names.
// Model, restated for anyone editing below: nothing is prepaid. Every fee — commission and
// reward — is deducted from what a creator-referred customer spends, settled weekly. Rates
// fall as the customer becomes a regular (15 / 8 / 4) and never expire.
// Density rule: this is a website, not the deck. One idea per block. Body copy in a column
// (Cols / Chrono / Steps) stays under ~3 lines; the deck's fourth sentence is always the cut.

export const en: Dict = {
  nav: { merchants: 'Merchants', creators: 'Creators', pricing: 'Pricing', security: 'Security', about: 'About', cta: 'Get early access', skip: 'Skip to content' },
  footer: {
    tagline: 'Financial infrastructure for local marketing.',
    fullPricing: 'Full pricing, caps and settlement',
    product: 'Product', company: 'Company', contact: 'Contact', legal: 'Legal',
    privacy: 'Privacy', terms: 'Terms', rights: 'All rights reserved.', built: 'Built in New York',
    investors: 'Investors',
  },
  form: {
    title: 'Get early access',
    lead: 'The first cohort opens in New York in Q4 2026. Tell us who you are and we will reach out when your neighborhood goes live.',
    role: { merchant: 'I run a store', creator: 'I am a creator' },
    fields: {
      name: 'Your name', email: 'Email', business: 'Business name', handle: 'Main account (Instagram / Xiaohongshu)',
      neighborhood: 'Neighborhood', note: 'Anything else', notePlaceholder: 'Category, a link, a question — optional.',
    },
    submit: 'Request access', submitting: 'Sending…',
    progress: 'Step 2 of 2 — you have already set your cap',
    capPrefix: 'Monthly cap',
    hoodDefault: 'New York',
    fallbackNote: 'This opens a prefilled email to hello@hibi.club. Nothing is stored on this site.',
    done: { title: 'Received.', body: 'Thank you — we read every request and reply from hello@hibi.club.' },
    error: 'Something went wrong. Email us directly at hello@hibi.club.',
  },

  home: {
    meta: {
      title: 'Hibi — Instagram sells impressions. Hibi sells walk-ins.',
      description: 'Financial infrastructure for local marketing. A creator posts with a code, the customer redeems it at your counter, and every fee comes out of that sale. Nothing prepaid, settled weekly. New York.',
    },
    eyebrow: 'Walk-in settlement · New York',
    title: ['Every walk-in', 'is a transaction', 'you can settle.'],
    lead: 'Instagram sells impressions. Google sells clicks. Hibi sells walk-ins. A local creator posts with a code, the customer redeems it at your counter, and the fee comes out of that sale.',
    ctaPrimary: 'Join as a merchant',
    ctaSecondary: 'Join as a creator',
    facts: ['Nothing paid upfront', 'Deducted from the sale, settled weekly', 'First cohort: New York, Q4 2026'],
    ledgerCard: {
      label: 'Sample settlement',
      period: 'Mar 2 – Mar 8',
      rows: [
        { who: '@mika.eats', meta: 'Thu 19:24 · first visit', amt: '$68.00', fee: '$10.20' },
        { who: '@bk.noodles', meta: 'Fri 12:05 · return', amt: '$41.50', fee: '$3.32' },
        { who: '@queens.list', meta: 'Sat 20:11 · first visit', amt: '$96.00', fee: '$14.40' },
        { who: '@mika.eats', meta: 'Sun 13:40 · regular', amt: '$28.00', fee: '$1.12' },
      ],
      pool: [
        { who: '@fort.greene', meta: 'Mon 12:31 · first visit', amt: '$54.00', fee: '$8.10' },
        { who: '@bk.noodles', meta: 'Mon 18:47 · return', amt: '$33.00', fee: '$2.64' },
        { who: '@queens.list', meta: 'Tue 13:02 · return', amt: '$61.50', fee: '$4.92' },
        { who: '@mika.eats', meta: 'Tue 20:15 · first visit', amt: '$88.00', fee: '$13.20' },
        { who: '@fort.greene', meta: 'Wed 11:58 · regular', amt: '$24.00', fee: '$0.96' },
        { who: '@bk.noodles', meta: 'Wed 19:33 · first visit', amt: '$47.50', fee: '$7.13' },
      ],
      totalLabel: '23 walk-ins · 4 creators',
      total: '$190.40',
    },
    problem: {
      label: 'The problem',
      title: 'Stores are billed on views and clicks. No platform can tell them who walked in.',
      a: { label: 'One creator campaign, paid upfront', num: '$3,000', body: 'The platform, the agency and the creator are all paid before a single customer shows up. Nobody counts which creator brought whom, so ROI is guessed, never known.' },
      b: { label: 'What a creator earns per customer delivered', num: '$0', body: 'Payouts are tied to posts, not customers. Most of any audience lives nowhere near the store — those views are paid for and can never become a visit.' },
      close: 'Stores overpay for attention. Creators go unpaid for outcomes. And nobody is paid for the second visit.',
    },
    how: {
      label: 'How it works',
      title: 'From a post to a paid visit, in three steps',
      steps: [
        { title: 'Post', body: 'A local creator visits and posts. The post carries a code that is theirs alone.' },
        { title: 'Counter', body: 'The customer shows it at checkout. Staff confirm the amount, and the reward opens.' },
        { title: 'Settlement', body: 'One line lands: who sent them, what they spent, what came out of the sale.' },
      ],
      recordTag: 'The record',
      record: 'One line per visit: creator, time, spend, first visit or return. Nobody else writes it — not the ad platforms, not the agencies, not the register.',
      demo: {
        label: 'Run a walk-in',
        hint: 'Tap redeem. The reward is drawn at the counter — usually part of the bill, occasionally all of it.',
        hintBack: 'Now send the same customer back. Watch the rate.',
        code: 'HIBI-M4K2',
        handle: '@mika.eats',
        redeem: 'Redeem',
        confirming: 'Confirming…',
        opening: 'Opening…',
        secFirst: 'first visit · reward drawn',
        secBack: 'returning · no reward drawn',
        rewardLabel: 'Reward',
        jackpotCap: 'Reward — the whole bill',
        jackpotNote: 'The commission is still owed on the bill. A whole-bill reward is the store’s own menu cost and lands on about one first visit in sixteen — priced in, not a surprise.',
        loyalty: 'points · better odds next time',
        paysLabel: 'Customer pays',
        credited: 'credited to this creator',
        uncredited: 'nothing owed yet',
        tiers: { first: 'first visit', return: 'return', regular: 'regular' },
        empty: 'Nothing to settle. Nothing owed.',
        ledgerFoot: '{n} settled this week',
        again: 'Same customer, next visit',
        doneNote: 'Five visits, one code, one customer. 15% → 4%, and the store keeps them.',
        over: 'Start over',
        rateNote: 'Same customer, same code. The rate falls; the record keeps counting.',
      },
    },
    sides: {
      label: 'Three sides, one transaction',
      title: 'Everyone is paid out of the same sale: a customer at the counter.',
      cols: [
        { label: 'Merchants', title: 'Marketing becomes a cut of the sale', body: 'Every fee is deducted from what those customers spend — first visit and every return. Nothing upfront, and the rate falls as they become a regular.' },
        { label: 'Creators', title: 'Influence becomes a sales force', body: 'Matched to stores their audience can actually walk into. No middlemen: paid per customer and per return, out of the same sales.' },
        { label: 'Customers', title: 'A reward becomes a reason to return', body: 'Not a coupon. A first visit wins up to the full bill; points, better odds and campaign perks bring them back.' },
      ],
      split: {
        total: '$100.00',
        totalLabel: 'a first-visit bill at the counter',
        parts: [
          { k: 'Merchant keeps', v: '$85.00', pct: 85 },
          { k: 'Creator earns', v: '$10.50', pct: 10.5 },
          { k: 'Hibi', v: '$4.50', pct: 4.5 },
        ],
        note: 'Pilot terms: 15% on a first visit, deducted from that sale. The creator keeps 70% of it. The reward is funded by the merchant out of the same sale, and nothing is charged to the customer.',
      },
    },
    marquee: 'Hibi sells walk-ins · 日々 · settled at the counter · ',
    pricing: {
      label: 'Pilot pricing',
      title: 'One commission. Three rates. Nothing else.',
      tiers: [
        { num: '15%', title: 'First visit', body: 'The first time a creator-referred customer redeems at your store.', unit: 'of the bill' },
        { num: '8%', title: 'Return visit', body: 'Every time that customer comes back to you.', unit: 'of the bill' },
        { num: '4%', title: 'Every visit after', body: 'From the fourth on, for as long as they keep coming.', unit: 'of the bill' },
      ],
      foot: 'No subscription, no setup fee, nothing prepaid. The rate only falls, and every regular keeps counting. You set the cap and the campaign length, and can pause anytime.',
      cta: 'See how it works for merchants',
    },
    now: {
      label: 'Why now',
      title: 'Everything this model needs has arrived — except the layer that holds it.',
      items: [
        { label: 'Demand', title: 'Results, not views', body: 'Software bills by usage, cloud by compute, services by results. The offline visit never could, because no one counted it. 79% of marketers call ROI the hardest part of influencer spend.' },
        { label: 'Proof', title: 'Visits are now an asset', body: 'Q1 2026: Wonder, Grubhub’s parent, bought Claim — cashback paid only after a visit. That put a price on three of our pillars. What Claim lacks is supply: it cannot see who created the intent.' },
        { label: 'The gap', title: 'The missing layer', body: 'Owners are handing daily operations to AI agents — Meituan is teaching 3.4M merchants. But every agent is a silo, and post → counter → payout is a chain no single one holds.' },
      ],
      close: 'Showing a code at a counter needs no explaining. The layer nobody owns is where Hibi starts.',
    },
    chain: {
      label: 'Who reaches how far',
      title: 'Everyone owns a piece of the chain. Nobody owns the chain.',
      links: ['Local creators', 'Post → visit', 'Paid on the visit', 'Creator paid per visit', 'Return rewarded'],
      rows: [
        { who: 'Hibi', what: 'walk-in settlement', has: [true, true, true, true, true], us: true },
        { who: 'Claim', what: 'card-linked cashback', has: [false, false, true, false, true] },
        { who: 'MCNs · creator agencies', what: 'paid per post', has: [true, false, false, false, false] },
        { who: 'Square · Toast', what: 'loyalty points', has: [false, false, false, false, true] },
        { who: 'Groupon', what: 'group deals', has: [false, false, false, false, false] },
        { who: 'Google · Yelp · Instagram', what: 'paid ads', has: [false, false, false, false, false] },
      ],
      none: 'None of it',
      caption: 'Claim is the closest, and the one thing it does better is card-linked detection — the customer never redeems at the counter. But it has no creators to source the visit, it is restaurants only, and it decides which ones get shown. Matching the full row means rebuilding a business around the counter.',
    },
    ai: {
      label: 'The record',
      title: 'One commission today. A record that compounds.',
      lead: 'Every redemption writes the line you played with above — creator, store, time, spend, return. A campaign of them is something no ad platform can produce, and three things are built on it.',
      items: [
        { label: 'Matching', title: 'Better creators, each run', body: 'A store’s own lines decide who gets matched to it next, and a new store starts from the block’s history instead of from zero.' },
        { label: 'Insights', title: 'What the neighborhood does', body: 'Which blocks draw customers, when, from where, how much they spend. Anonymized and aggregated, sold to stores, landlords and brands.' },
        { label: 'Creators', title: 'A record worth buying', body: 'A creator who can prove paying customers, not views, gets priced on it — by our matching, and by brands who buy them out.' },
      ],
      close: 'And every campaign leaves the store regulars, billed at 4% instead of 15%.',
    },
    start: {
      label: 'Where we start',
      title: 'New York. One neighborhood at a time.',
      body: 'Two dense neighborhoods, the first hundred stores, each with its own local creators. Restaurants, coffee, beauty and nails, fitness, local retail — any counter with an average ticket of $15 or more. Ground sales begin Q4 2026.',
      ctaMerchant: 'Join as a merchant',
      ctaCreator: 'Join as a creator',
    },
  },

  merchants: {
    meta: {
      title: 'Hibi for merchants — marketing you pay for out of the sale',
      description: 'Set a fee per customer, a monthly cap and a campaign length. Local creators send customers; the fee comes out of what they spend at your counter. Nothing prepaid, settled weekly.',
    },
    eyebrow: 'For merchants',
    title: 'Marketing becomes a cut of the sale.',
    lead: 'You set the fee per customer, the monthly cap and how long the campaign runs. Local creators bring the customers, and every fee comes out of what those customers spend — nothing before one walks in.',
    heroCard: {
      label: 'What you pay',
      rows: [
        { k: 'First visit', v: '15%', u: 'of the bill' },
        { k: 'Return visit', v: '8%', u: 'of the bill' },
        { k: 'Every visit after', v: '4%', u: 'of the bill' },
        { k: 'Monthly cap', v: 'Yours', u: 'set it, pause anytime' },
      ],
      foot: 'No subscription, no setup fee, nothing prepaid. Deducted from the sale, settled weekly.',
    },
    set: {
      label: 'What you set',
      title: 'Your cap is not a budget. It is a number of people.',
      billLabel: 'Your average bill',
      capLabel: 'Monthly cap',
      lengthLabel: 'How long the campaign runs',
      lengths: ['2 weeks', '1 month', '3 months', 'Leave it open'],
      peopleLabel: 'What that cap buys, in people',
      perNote: 'new customers a month, at 15% — {each} each. Nothing is charged until one of them walks in.',
      tiers: { first: 'First visits', ret: 'Return visits', regular: 'Visits by regulars' },
      stretch: 'A first visit costs you {a}. Once that person is a regular, {b}. Same cap, three times the people.',
      exposureLabel: 'Most this campaign can cost',
      exposureNote: 'and only on customers who actually walked in',
      exposureOpenLabel: 'No end date, so no total ceiling',
      exposureOpenNote: 'a month at most, and one tap pauses it',
      note: 'The fee is 15% of a first visit, 8% of a return, 4% once they are a regular, and it exists only where someone redeemed at your counter. When commission reaches your cap the campaign pauses itself — raise it, lower it or stop at any time. The reward a first-timer wins, up to the full bill, is funded out of that same sale.',
    },
    counter: {
      label: 'At the counter',
      title: 'One tap by staff. Under five seconds.',
      body: 'No new hardware and no POS integration for the pilot. Staff open Hibi, scan the code, confirm the amount — in bad light, at a busy counter, on a cashier’s first day.',
      steps: [
        { title: 'Customer shows the code', body: 'One code per creator, one use per customer.' },
        { title: 'Staff confirm the amount', body: 'Scan, enter what they spent, done. Both sides confirm the same number.' },
        { title: 'The reward opens', body: 'It resolves on the spot, and the creator is credited in the same tap.' },
      ],
    },
    bill: {
      label: 'The settlement',
      title: 'One settlement a week. Every line is a customer.',
      body: 'Each redemption writes one line: which creator, what time, what they spent, whether they came back. The fee comes out of those sales and settles weekly — every dollar reads back to a person at your counter.',
      ledger: 'One illustrative week: 23 walk-ins · 6 posts by 4 creators · $1,725 in sales · $190 in commission',
      note: 'Figures are illustrative. Actual numbers come from the first cohort of stores.',
    },
    pricing: {
      label: 'Pilot pricing',
      title: 'One commission. Three rates.',
      tiers: [
        { num: '15%', title: 'First visit', body: 'A customer’s first redemption at your store.', unit: 'of the bill' },
        { num: '8%', title: 'Return visit', body: 'Every time that customer comes back.', unit: 'of the bill' },
        { num: '4%', title: 'Every visit after', body: 'From the fourth on, for as long as they keep coming.', unit: 'of the bill' },
      ],
      foot: 'The rate falls as a customer becomes a regular, so each campaign leaves you cheaper traffic than it found. Pilot pricing; final rates are set with the first cohort and published here.',
    },
    faq: {
      label: 'Questions',
      title: 'What merchants ask first',
      items: [
        { q: 'How is this different from Instagram or Google ads?', a: 'Those bill you before anyone shows up, for views and clicks, and no platform can tell you who walked in. Hibi takes a cut of a sale that already happened at your counter.' },
        { q: 'Do I have to pay anything upfront?', a: 'No. Fee, commission and reward all come out of what creator-referred customers spend, settled weekly. Topping up a balance is optional — it earns a verified badge and keeps creator payouts on time.' },
        { q: 'Who are the creators?', a: 'Local, mid-tier creators — typically 3K to 100K followers on Instagram or Xiaohongshu — matched to stores their audience can walk into. Paid per customer, not per post.' },
        { q: 'What kind of store is this for?', a: 'Restaurants, coffee, beauty and nails, fitness, local retail — any brick-and-mortar business with an average ticket of $15 or more.' },
        { q: 'Do I need new hardware or a POS integration?', a: 'Not for the pilot. Staff use Hibi on any phone or tablet. POS integrations follow once the first cohort is running.' },
        { q: 'How do you prevent fake redemptions?', a: 'One code per creator, one use per customer, staff confirmation at the counter, and outlier detection on timing, amount, device and location. Anything unusual is held for a person before it settles.' },
        { q: 'Where is Hibi available?', a: 'Two dense New York neighborhoods first, from Q4 2026. Request access and we will tell you when yours opens.' },
      ],
    },
  },

  creators: {
    meta: {
      title: 'Hibi for creators — paid per customer you send',
      description: 'Your commission comes out of the sales you create, with no flat-fee ceiling. Every return visit keeps paying. A Creator Passport that proves conversion, not reach.',
    },
    eyebrow: 'For creators',
    title: 'Influence becomes a sales force.',
    lead: 'Post about places you actually go. Every customer who redeems your code pays you a commission out of that sale — on their first visit, and on every return after it.',
    heroCard: {
      label: 'What you earn',
      rows: [
        { k: 'Per first visit', v: '10.5%', u: 'of the bill — 70% of a 15% commission' },
        { k: 'Per return visit', v: '4.4%', u: 'of the bill — 55% of the 8% return rate' },
        { k: 'Paid out', v: 'Weekly', u: 'no invoicing, no chasing' },
        { k: 'Follower minimum', v: 'None', u: 'delivered customers count' },
      ],
      foot: 'No flat fees, no agency cut, no middlemen. Paid out of sales that actually happened.',
    },
    why: {
      label: 'Why creators join',
      title: 'No flat fees. No agency cut. No follower minimum.',
      cols: [
        { label: 'Uncapped', title: 'Your income has no ceiling', body: 'Your commission comes out of the sales you created, so it grows with every customer you deliver — not with a rate you negotiated once.' },
        { label: 'Trailing', title: 'Past work keeps paying', body: 'You are paid on the first visit and on every return that customer makes. A post from March is still paying in December.' },
        { label: 'Passport', title: 'Proof of conversion, not reach', body: 'Every customer you bring is stamped at the counter. Followers can be bought; a paying customer cannot. Tiers unlock higher-value stores.' },
      ],
    },
    how: {
      label: 'How it works',
      title: 'Four steps, weekly payout',
      steps: [
        { title: 'Pick a store brief', body: 'Stores near you publish the fee, the reward, the cap and how long it runs.' },
        { title: 'Visit and post', body: 'Publish on Instagram or Xiaohongshu, carrying a code that is yours alone.' },
        { title: 'Customers redeem', body: 'Each redemption is one line in your ledger: store, time, spend, what you earned.' },
        { title: 'Get paid weekly', body: 'Straight out of the sales you created. Returns keep landing without a new post.' },
      ],
    },
    split: {
      label: 'The split',
      title: 'On a $100 first-visit bill',
      body: 'The store’s fee on a first visit is 15% of the bill, deducted from that sale, and you keep 70% of it. On returns the fee is 8% — 4% once the customer is a regular — and you keep 55% of that, every time they come back.',
      s: {
        total: '$15.00',
        totalLabel: 'the commission on a $100 first visit',
        parts: [
          { k: 'You keep', v: '$10.50', pct: 70 },
          { k: 'Hibi', v: '$4.50', pct: 30 },
        ],
        note: 'Pilot terms. Rates are confirmed with the first cohort and published here.',
      },
    },
    calc: {
      label: 'Against the fee you get now',
      title: 'A flat fee is paid once. This one keeps going.',
      lead: 'Put in your own rate card. If the flat fee wins at your numbers, the figure says so — we would rather you find that out here than in month three.',
      billLabel: 'Average bill at the store',
      visitsLabel: 'Customers you send per month',
      flatLabel: 'What you get for one post today',
      hibiLabel: 'Hibi, cumulative',
      flatSeriesLabel: 'Flat fee, paid once',
      crossLabel: 'You pass the flat fee in',
      crossMonth: 'Month {n}',
      crossNeverLabel: 'At these numbers',
      crossNever: 'Not within a year',
      yearLabel: 'Twelve months: {hibi} here, against {flat} once.',
      monthAxis: 'Month {n}',
      note: 'You keep 70% of the first-visit commission (15% of the bill) and 55% of every return commission (8%, then 4% once they are a regular). The line climbs because customers you sent in March are still coming back in December. Assumes each returns every other month.',
      cta: 'Apply as a creator',
    },
    faq: {
      label: 'Questions',
      title: 'What creators ask first',
      items: [
        { q: 'How many followers do I need?', a: 'No threshold. We work with local, mid-tier creators — roughly 3K to 100K on Instagram or Xiaohongshu. What matters is whether the people who follow you go where you go.' },
        { q: 'Is there an agency or a middleman?', a: 'No. You take a brief directly from the store and are paid directly out of the sales you create.' },
        { q: 'Is it exclusive?', a: 'No. Post for whichever stores you like, on whichever platforms you like.' },
        { q: 'When and how do I get paid?', a: 'Weekly, to your bank account, once your delivered customers have been confirmed at the counter.' },
        { q: 'What counts as a delivered customer?', a: 'Someone who shows your code, has the amount confirmed by staff, and passes automated risk checks. One code per creator, one use per customer.' },
        { q: 'What is the Creator Passport?', a: 'Your record of customers delivered, stamped at the counter rather than claimed in a media kit. It sets your tier, which unlocks higher-value stores and better matches.' },
        { q: 'Where is this available?', a: 'New York first, one neighborhood at a time, from Q4 2026. Instagram and Xiaohongshu at launch.' },
      ],
    },
  },

  about: {
    meta: {
      title: 'About Hibi',
      description: 'Hibi (日々, “day by day”) is a New York company building financial infrastructure for local marketing: the fee comes out of the sale a customer actually made, and the person who sent them is paid from the same one.',
    },
    eyebrow: 'About',
    title: 'Hibi — 日々, day by day.',
    lead: 'A small team in New York building financial infrastructure for local marketing: a store pays out of the sale a customer actually made, and the person who sent them is paid from the same one.',
    heroCard: {
      label: 'The facts',
      rows: [
        { k: 'Based in', v: 'New York', u: 'one neighborhood at a time' },
        { k: 'First cohort', v: 'Q4 2026', u: 'merchants and creators, forming now' },
        { k: 'Reach us', v: 'Directly', u: 'hello@hibi.club — every message is read' },
      ],
      foot: 'Everything above is current. We publish pilot results, not projections.',
    },
    what: {
      label: 'What we are building',
      title: 'The unit a store pays for should be a customer walking through the door.',
      paras: [
        'A local store is billed on views and clicks, and no platform can tell it who walked in. Local creators send customers to that same store every week — and because nobody counts it, they are not paid for it.',
        'Hibi counts it at the counter. A creator posts with a code, a customer redeems it, and every fee comes out of that one sale. Marketing stops being a budget spent in advance and becomes a cut of revenue that already exists.',
        'We are not a marketplace. Marketplaces sell matches, and matches get bypassed. One scan here writes three records — the store’s, the creator’s Passport, the customer’s history — and they meet at settlement.',
      ],
    },
    principles: {
      label: 'How we work',
      title: 'Four commitments',
      cols: [
        { label: '01', title: 'No numbers before data', body: 'Pilot results, not projections. No scale narrative before the first cohort produces its three: stores that run a second campaign, net new return visits, creators who stay unsubsidized.' },
        { label: '02', title: 'Customers are never charged', body: 'Redeeming a code is claiming a reward. Nothing more is asked, and nothing is added to their bill.' },
        { label: '03', title: 'No selling of personal data', body: 'Insights leave anonymized and aggregated — a neighborhood, never a person and never a list.' },
        { label: '04', title: 'No exclusivity, no rankings, no paid reviews', body: 'Creators post where they like, stores set their own terms. Merchants buy customers, not praise.' },
      ],
    },
    hiring: {
      label: 'Open roles',
      title: 'Nine seats, hired in New York before and during the pilot',
      note: 'Pre-funding, said plainly: early team seats under a written advisor agreement, not salaried employment, and no cash compensation today. Targets are written down in your first two weeks and equity is earned against them; the first compensation offers go to people already here, within 30 days of the angel round closing.',
      roles: [
        { label: 'Engineering', title: 'Technical lead', body: 'Prototype to 1.1, then hires the team. Sets the stack, the cadence and the quality bar. Ships weekly with the founder.' },
        { label: 'Engineering', title: 'Systems architect', body: 'The settlement ledger: scan verification, fee splits, payouts, anti-fraud, Stripe rails. One checkout, three records.' },
        { label: 'Design', title: 'UI/UX designer', body: 'Counter flow, creator app, customer reward flow. Takes the prototype to production and keeps five seconds honest.' },
        { label: 'Finance', title: 'Finance & payments', body: 'Money movement and compliance: Stripe Connect, settlement accounting, creator tax forms, state-by-state rules.' },
        { label: 'Data', title: 'Data & risk lead', body: 'The record itself: data quality, anti-fraud rules, matching signals, and the analytics that become Insights.' },
        { label: 'Partnerships', title: 'Creator partnerships', body: 'Sourcing, matching, briefs, Passport tiers, disputes. Knows every creator by name.' },
        { label: 'Sales', title: 'Ground sales agents', body: 'Bilingual, block by block. Sign stores, train staff on the scan, onboard creators, keep both sides live.' },
        { label: 'Operations', title: 'Operations manager', body: 'Weekly settlements, disputes, payouts, store support, reward inventory. Turns the record into a bill stores read.' },
        { label: 'Marketing', title: 'Marketing & outreach', body: 'Brand, community and press. Launch events, referrals, word of mouth. Earned channels — Hibi does not buy impressions.' },
      ],
      cta: 'Write to us',
    },
    investors: {
      label: 'Investors',
      title: 'Pre-seed, New York',
      body: 'Raising a pre-seed on a YC post-money SAFE to run the first cohort: a ground team in two New York neighborhoods, product from 1.0 to 1.1, and creator payouts funded from day one. Materials on request.',
      cta: 'Request the deck',
    },
  },

  pricing: {
    meta: {
      title: 'Hibi pricing — one commission, three rates',
      description: 'No subscription, no setup fee, nothing prepaid. A commission deducted from what a creator-referred customer spends: 15% first visit, 8% return, 4% once they are a regular. Pilot pricing, New York.',
    },
    eyebrow: 'Pricing',
    title: 'You pay out of what they spend.',
    lead: 'One kind of charge: a percentage of what a creator-referred customer actually spent at your counter, deducted from that sale. No subscription, no setup fee, nothing prepaid, and a monthly cap you set.',
    rates: {
      label: 'The rates',
      title: 'One commission. Three rates.',
      tiers: [
        { num: '15%', title: 'First visit', body: 'The first time a creator-referred customer redeems at your store.', unit: 'of the bill' },
        { num: '8%', title: 'Return visit', body: 'Every time that customer comes back to you.', unit: 'of the bill' },
        { num: '4%', title: 'Every visit after', body: 'From the fourth on, for as long as they keep coming.', unit: 'of the bill' },
      ],
    },
    calc: {
      label: 'What it would cost you',
      title: 'The 15% is only the first visit. Watch the rate fall.',
      lead: 'Set your numbers — nothing is sent anywhere, and the cap carries into the form below. Set the third one to “never comes back” and the rate stays at 15% all year, which is the honest worst case.',
      spendLabel: 'Average bill per customer',
      visitsLabel: 'New walk-ins per month',
      returnLabel: 'How often does a customer come back?',
      returnOpts: ['Never', 'Twice a year', 'Every other month', 'Every month'],
      blendedLabel: 'What you actually pay, blended over a year',
      blendedNote: 'Month one is 15%, because every customer is new.',
      ceilLabel: '15% · every visit a first visit',
      monthAxis: 'Month {n}',
      yearLabel: 'Year one, total commission',
      yearNote: 'on {sales} of sales you would not have had',
      capLabel: 'Set this as your monthly cap',
      capNote: 'Sized to month one — the most expensive month, when nobody is a regular yet. Rounded up to the nearest $25.',
      note: '15% on a first visit, 8% on a return, 4% from the fourth on. The blend falls because the returns pile up underneath, and every one of them is a customer you keep.',
      cta: 'Apply with this cap',
    },
    free: {
      label: 'Not billed',
      title: 'Everything else is zero.',
      items: [
        'No subscription',
        'No setup or onboarding fee',
        'No upfront payment of any kind',
        'No minimum term',
        'No charge for posts that bring nobody',
        'No charge for the creator’s content',
        'No hardware to buy',
      ],
      note: 'A post that produces no walk-in costs you nothing. That is the whole difference from ad spend.',
    },
    compare: {
      label: 'Against ad spend',
      title: 'The same money, two ways.',
      body: 'A creator campaign, or a month across Instagram, Google and Yelp, is paid before anyone shows up. Below is the same money run as a cut of sales instead.',
      adsHead: 'Ad spend',
      hibiHead: 'Hibi',
      rows: [
        { k: 'Paid', ads: 'Before anyone shows up', hibi: 'Out of the sale, after they redeem' },
        { k: 'Priced on', ads: 'Views and clicks', hibi: 'What the customer actually spent' },
        { k: 'If nobody comes', ads: 'You still paid', hibi: 'You owe nothing' },
        { k: 'Who brought them', ads: 'Unknown', hibi: 'One line per customer, named to a creator' },
        { k: 'The second visit', ads: 'Nobody is paid for it', hibi: 'Rewarded, at a lower rate' },
        { k: 'Ceiling', ads: 'Your budget', hibi: 'A cap you set, pausable anytime' },
      ],
    },
    faq: {
      label: 'Questions',
      title: 'What merchants ask about price',
      items: [
        { q: 'What do I pay if nobody comes?', a: 'Nothing. The commission exists only where a customer redeemed at your counter, and it comes out of that sale. No floor, no subscription underneath it.' },
        { q: 'When am I charged?', a: 'Never in advance. Fees come out of the sales they were earned on and settle weekly, each line naming the creator, the time, the amount and the commission.' },
        { q: 'Is the reward part of the commission?', a: 'No. The reward is funded out of the same sale, up to the full bill, and is set by you. The commission is separate.' },
        { q: 'Does the rate ever go back up?', a: 'No. It only falls — 15%, 8%, then 4% once they are a regular — and stays there for as long as that customer keeps coming back.' },
        { q: 'How is the cap enforced?', a: 'When commission reaches your monthly cap, your codes stop being billable for the rest of the month. Raise it, lower it or pause at any time.' },
        { q: 'Will these rates change?', a: 'These are pilot rates. Final rates are set with the first cohort and published here — pilot merchants keep their pilot rate through the pilot.' },
      ],
    },
  },

  security: {
    meta: {
      title: 'Hibi security — how a redemption is verified',
      description: 'What happens to a redemption and to the data around it: one-use codes, counter confirmation, outlier review, weekly settlement on Stripe rails. Pilot stage, stated plainly.',
    },
    eyebrow: 'Security',
    title: 'A redemption is a claim about money.',
    lead: 'So it is treated like one. Every code is single-use, every redemption is confirmed by your own staff, and anything that looks unlike the rest goes to a person before a cent of it settles.',
    pillars: {
      label: 'Safeguards',
      title: 'What we hold ourselves to',
      cols: [
        { label: 'Verification', title: 'The counter is the source of truth', body: 'A code is worth something only once your staff confirms the amount. Nothing settles off a screenshot, a link, or a claim made after the fact.' },
        { label: 'Payment', title: 'We never touch your card data', body: 'Customers pay you on your own terminal, exactly as today. Hibi settles the commission separately and never sits in the payment path.' },
        { label: 'Data', title: 'No personal data is sold', body: 'Insights leave anonymized and aggregated — a neighborhood, never a person and never a list. You see your customers; nobody buys them.' },
        { label: 'Money out', title: 'One weekly settlement', body: 'Fees come out of the sale they were earned on, weekly, on Stripe Connect rails. A dispute pauses that line, not the whole settlement.' },
      ],
    },
    redemption: {
      label: 'The check',
      title: 'What has to be true before a line settles',
      steps: [
        { title: 'The code is live and unused', body: 'One code per creator per campaign, one use per customer. Spent, expired and paused codes stop at the counter.' },
        { title: 'Your staff confirms the amount', body: 'The redemption records what your staff enters — both sides confirm the same number before anything is written.' },
        { title: 'The pattern holds up', body: 'Timing, amount, device and location are scored against the store’s own history. Outliers are held for review instead of settling.' },
      ],
      note: 'A held line does not delay the rest of your settlement. It either clears into the following week or is dropped.',
    },
    data: {
      label: 'The record',
      title: 'What we keep, and for whom',
      rows: [
        { k: 'Per redemption', v: 'Store, creator code, time, amount spent, commission, first visit or return' },
        { k: 'The merchant sees', v: 'Their own redemptions, in full' },
        { k: 'The creator sees', v: 'The customers they sent, and what they earned' },
        { k: 'The customer', v: 'Identified only as far as preventing a second use of the same reward' },
        { k: 'Insights reports', v: 'Anonymized and aggregated — a block and a time, never a person' },
        { k: 'Personal data sold', v: 'Never' },
        { k: 'On request', v: 'Export or deletion by email — see Privacy' },
      ],
      note: 'This site itself sets no tracking cookies and runs no third-party advertising scripts.',
    },
    stage: {
      label: 'Where we are',
      title: 'What we have not done yet.',
      body: 'Hibi is pre-launch. We would rather say what is missing than imply a maturity we have not earned:',
      items: [
        'No production traffic yet — the first stores go live in Q4 2026',
        'No SOC 2 or ISO audit yet, and no uptime history to publish',
        'Pilot terms are contracts we can still change with the first cohort',
      ],
      cta: 'Ask us about any of this',
    },
  },

  legal: {
    meta: { title: 'Privacy & Terms — Hibi', description: 'Privacy policy and terms of service for hibi.club.' },
    eyebrow: 'Legal',
    title: 'Privacy & Terms',
    updated: 'Last updated: September 6, 2026',
    notice: 'Draft for the pilot period. These terms will be replaced by counsel-reviewed versions before the first cohort goes live.',
    privacy: {
      title: 'Privacy policy',
      sections: [
        { h: 'What this site collects', p: ['This website does not set tracking cookies and does not run third-party advertising scripts. If you submit the early-access form, we receive the fields you typed (name, email, business or account name, neighborhood, note) and use them only to contact you about Hibi.'] },
        { h: 'Product data (pilot)', p: ['When the Hibi product is live, a redemption records the store, the creator code, the time, the amount spent, the commission, and whether it was a first visit or a return. This record is used to settle merchants, pay creators, and detect fraud. Merchants see redemptions at their own store. Creators see their own deliveries. Customers are identified only as needed to prevent duplicate redemptions.', 'We do not sell personal data. Insights reports that leave the system are anonymized and aggregated — a neighborhood and a time of day, never a person and never a list.'] },
        { h: 'Retention and your rights', p: ['We keep form submissions until you ask us to delete them. Email hello@hibi.club to access, correct or delete anything we hold about you.'] },
        { h: 'Contact', p: ['Hibi, New York. hello@hibi.club'] },
      ],
    },
    terms: {
      title: 'Terms of service',
      sections: [
        { h: 'This website', p: ['hibi.club is an informational site. Requesting early access creates no obligation on either side. We may change the site and these terms at any time; the date above tells you when we last did.'] },
        { h: 'Pilot participation', p: ['Merchants and creators who join the pilot sign a separate participation agreement that sets out commissions, settlement timing, code rules and fraud policy. Where that agreement and this page differ, the agreement controls.'] },
        { h: 'Codes and redemptions', p: ['A redemption code is one use per customer. Self-redemption, redemption by staff on their own behalf, or coordinated redemption without a real purchase are grounds for withheld commission and removal from the program.'] },
        { h: 'Roles and materials', p: ['Pages describing open roles state an intent to collaborate. They are not an offer of employment, an employment contract, or an offer of any kind; all rights and obligations are governed by separately signed written agreements.'] },
        { h: 'Liability', p: ['The site is provided as is. To the extent permitted by law, Hibi is not liable for indirect or consequential loss arising from use of this site.'] },
      ],
    },
  },
};
